// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-Py4o66E8qW99cS-3aGQBlpDt6yTpi-Q',
    appId: '1:784917770847:web:92277ca5be96927ac021ea',
    messagingSenderId: '784917770847',
    projectId: 'furniture-843ca',
    authDomain: 'furniture-843ca.firebaseapp.com',
    storageBucket: 'furniture-843ca.firebasestorage.app',
    measurementId: 'G-M9J3909FDE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBziejB7OXkJWzPO3llyCzuA8l5mxxfCOQ',
    appId: '1:784917770847:android:958748f5fc2d4adac021ea',
    messagingSenderId: '784917770847',
    projectId: 'furniture-843ca',
    storageBucket: 'furniture-843ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl8yT-ORqCbIuPtqK1p2fR659_dq5PSys',
    appId: '1:784917770847:ios:513c16f6b7e3ee81c021ea',
    messagingSenderId: '784917770847',
    projectId: 'furniture-843ca',
    storageBucket: 'furniture-843ca.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAl8yT-ORqCbIuPtqK1p2fR659_dq5PSys',
    appId: '1:784917770847:ios:513c16f6b7e3ee81c021ea',
    messagingSenderId: '784917770847',
    projectId: 'furniture-843ca',
    storageBucket: 'furniture-843ca.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-Py4o66E8qW99cS-3aGQBlpDt6yTpi-Q',
    appId: '1:784917770847:web:c49c9639e2b91fe6c021ea',
    messagingSenderId: '784917770847',
    projectId: 'furniture-843ca',
    authDomain: 'furniture-843ca.firebaseapp.com',
    storageBucket: 'furniture-843ca.firebasestorage.app',
    measurementId: 'G-8HVGTLZP7G',
  );
}
